### ISSUE TITLE
[Windows] Required library with BLAS API not found

### ISSUE THREAD

**Issue by JohanMabille** [conda-forge/blas-feedstock#10]
When building with cmake + nmake on windows, `find_package(BLAS)` leads to:

```bash
A required library with BLAS API not found.  Please specify library location.
```

**Comment by jakirkham** [comment]
So this is a metapackage for selecting a BLAS. It is not a BLAS itself. Further we don't actually have a BLAS built for Windows yet. Currently Windows users are using MKL provided by Continuum, which doesn't include dev files like this. That said, we would be very interested in having a BLAS for Windows that is supported in conda-forge. For some history please see the linked issues below and please feel free to contribute. Would love some kind of solution for this. Going to close in favor of furthering those discussions.

xref: https://github.com/conda-forge/openblas-feedstock/issues/2
xref: https://github.com/conda-forge/numpy-feedstock/issues/46
