### ISSUE TITLE
blas variants

### ISSUE THREAD

**Issue by isuruf** [conda-forge/blas-feedstock#15]
Compiling against different blas and lapack versions for downstream packages is insane in my opinion given that the libraries are ABI compatible. Shall we go for an approach like Debian's update-alternatives?

Here's my proposal.

We have `libblas=3.8.0=netlib` with `libblas.so.3` and downstream packages compile and link against this library. openblas and mkl also provides `libblas=3.8.0=openblas`, `libblas=3.8.0=mkl` conda packages with build string openblas and mkl and in those packages, they symlink/hardlink `libblas.so.3` to `libopenblas.so` or `libmkl_rt.so`

In this way, there needs to be one variant of the downstream package and the user can pick whatever blas implementation they need.

cc @conda-forge/core, @mingwandroid

**Comment by mingwandroid** [comment]
CCing @msarahan, @jjhelmus, @kalefranz, @mcg1969 (but please, continue with your Thanksgiving celebrations) and @nehaljwani.

This sounds really cool to me @isuruf, but if we want to do this, I'd love to have some test (split) package that runs a good blas testsuite over each one on all OSes.

We did run into some symbol incompatibilities on Windows between MKL 2017  and MKL 2018. I have not dug into the details though, Mike S probably knows more.

**Comment by nehaljwani** [comment]
I am open to the idea too, however, how would the versioning of this meta package be done? In this example, what does v3.8.0 signify?

**Comment by isuruf** [comment]
3.8.0 is the reference BLAS/LAPACK version

**Comment by isuruf** [comment]
https://github.com/conda-forge/lapack-feedstock/pull/15 is how the netlib packages would look like. Can't go further without fixing https://github.com/conda/conda-build/pull/3264#issuecomment-441044559

**Comment by isuruf** [comment]
I've uploaded `libblas, libcblas, liblapack, liblapacke` to isuruf channel, if anyone wants to play with them. (netlib and openblas variants)

I've also uploaded numpy for python 3.6 with the following change.
```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index e05a989..c77c72a 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,5 +1,4 @@
 {% set version = "1.15.4" %}
-{% set variant = "openblas" %}
 
 package:
   name: numpy
@@ -14,8 +13,6 @@ source:
 build:
   number: 1000
   skip: true  # [win32 or (win and py27)]
-  features:
-    - blas_{{ variant }}
 
 requirements:
   build:
@@ -25,13 +22,10 @@ requirements:
   host:
     - python
     - pip
-    - cython
-    - blas 1.1 {{ variant }}
-    - openblas
+    - libblas * *netlib
+    - libcblas * *netlib
   run:
     - python
-    - blas 1.1 {{ variant }}
-    - openblas
 
 test:
   requires:
```

`conda install numpy python=3.6 -c isuruf` gives you an openblas build
`conda install numpy python=3.6 "libblas=*=*netlib" -c isuruf` gives you a netlib build with the same numpy build

**Comment by isuruf** [comment]
Also uploaded mkl and blis variants

**Comment by isuruf** [comment]
recipes for mkl, openblas, blis variants are at https://github.com/conda-forge/blas-feedstock/pull/16

**Comment by isuruf** [comment]
ping

**Comment by mingwandroid** [comment]
Thanks @isuruf, some of the AD team are out of action at present but rest assured this important work will not be forgotten about!

**Comment by msarahan** [comment]
We very painfully learned that mkl is not strictly forward compatible. With anaconda 5.3.0, we included mkl 2019, but all our packages had been built with mkl 2018. There were some really about problems, especially on windows. Intel advised us that mkl is only strictly compatible with a given major version, which is roughly yearly.

Maybe openblas works better. I think it's worth a try.

**Comment by msarahan** [comment]
Also note that our numpy build has huge patches from Intel that use proprietary mkl stuff. Those patches won't work with openblas. Sorry to rain on the parade, but I think relaxing run_exports for openblas might be the best you can do here.

**Comment by isuruf** [comment]
Can you point me to some references on these bugs? Do they occur when using MKL internals or BLAS and LAPACK API?

**Comment by msarahan** [comment]
I think these were the issues: https://github.com/ContinuumIO/anaconda-issues/issues/10182

**Comment by isuruf** [comment]
This seems to be a windows only issue. Have you been able to reproduce this locally? If so, can you archive the environment files and post it somewhere?

**Comment by isuruf** [comment]
> Also note that our numpy build has huge patches from Intel that use proprietary mkl stuff. Those patches won't work with openblas.

For these cases, you can build for different blas implementations and I think there aren't many libraries depending on MKL or openblas specifics.

**Comment by scopatz** [comment]
Ahh I see that makes sense

**Comment by isuruf** [comment]
I just uploaded windows packages to my channel and they work as well. I tested by building a test program with netlib package and after changing to mkl or blis or openblas it still worked. I haven't done any testing on OSX because I don't have access to a OSX machine.

(Windows packages copy instead of using symlinks. @mingwandroid said symlinks might work on windows. I'll try that later)

**Comment by mingwandroid** [comment]
They work at the lowest level in that you can make packager containing them and those packages will work..  with caveats. Mostly that developer mode is required in build and host machines. I'd recommend avoiding them until we have more comprehensive support and tests in place. The fallback is very important and directory symlinks are also important.

**Comment by isuruf** [comment]
@msarahan, MKL issue was probably because some internal MKL dll was using a ordinal only scheme, but the BLAS/LAPACK API is exported by name so that other applications can directly load the DLL and access the function by name. If a library is using MKL API not in BLAS/LAPACK, they have to pin to the major version.

In https://github.com/conda-forge/blas-feedstock/pull/16 I built the LAPACK testsuite against netlib libraries and in the testing environment switched to the other implementations (mkl, openblas and blis) without recompiling the tests. Test-suite mainly passes. MKL doesn't pass some tests and that happens even when LAPACK testsuite is built against MKL normally. Same with Windows and OpenBLAS. Note that none of the tests fail with symbols missing which means MKL, OpenBLAS and BLIS correctly exports all the functions in 3.8.0.

The two PRs https://github.com/conda-forge/blas-feedstock/pull/16 and https://github.com/conda-forge/lapack-feedstock/pull/15 are ready for review.

**Comment by isuruf** [comment]
Ping. I can discuss this in a conda-forge meeting, if anyone likes to.

**Comment by scopatz** [comment]
I think that is a good idea.  I don't see a big impediment to restructuring here.

**Comment by isuruf** [comment]
Thanks. I'll release blas 2.0 which shouldn't affect existing packages.

**Comment by isuruf** [comment]
Done in #16

**Comment by scopatz** [comment]
:tada:
