### ISSUE TITLE
libblas_mkl_deactivate.sh incompatible with zsh

### ISSUE THREAD

**Issue by croth1** [conda-forge/blas-feedstock#25]
The `==` in libblas_mkl_deactivate.sh is bash compatible, but not valid zsh syntax. This is giving me following error:

> /Users/christian/miniconda3/envs/sci36/etc/conda/deactivate.d/libblas_mkl_deactivate.sh:1: = not found

**Comment by isuruf** [comment]
I don't use zsh, so can't fix this. PRs are welcome.

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/blas-feedstock/pull/26. Thanks
