### ISSUE TITLE
Include the BSD license file in the installed conda package

### ISSUE THREAD

**Issue by tylere** [conda-forge/blas-feedstock#3]
The BLAS conda package does not contain a license file. For a concrete example see the following tar file:
https://conda.anaconda.org/conda-forge/linux-64/blas-1.1-openblas.tar.bz2

Unlike other feedstock repos that I have looked at, I did not find a source url in the meta.yaml file, so I am unsure where to look for the license file.

**Comment by jakirkham** [comment]
Yeah, this one is weird as it is a metapackage. So there isn't source with it per se. It's main purpose is to help one select what BLAS the stack uses. ATM that is OpenBLAS, but there are other BLASes we would like to provide as options.

That's correct this doesn't contain a license file and you are right that it should. I believe we were intending to license it with the standard conda-forge BSD 3-Clause license. Does that sound correct to you, @pelson? I'll drum up a PR along those lines and you can let me know there.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/blas-feedstock/pull/4 ).

**Comment by pelson** [comment]
@jakirkham - I'm not sure we *need* a license in this metapackage. It isn't that I have an objection to doing so, just reluctant to add extra maintenance burden.

@tylere - just wondering if, now that you know that this blas meta package just pulls in one of openblas or MKL as dependencies (i.e. it results in another package being installed), you would still expect the empty "blas" package to have a license file?

**Comment by tylere** [comment]
My primary goal is to ensure that any package installed by conda in the [Jupyter Notebook Data Science Stack](https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook) has a proper license file included with it. Because the stack includes >200 packages that are mix of conda-forge and anaconda packages with various methods of providing licensing information and completeness, I am attempting to programmatically work through the list of packages.

Because the blas metapackage is empty I don't see a need for a license file for the package content.  I can just have my script look in the files folder and note that nothing is installed.  Or is there an easy way to test that it is a metapackage from the meta.yaml file (like source:url is missing). 

On the other hand, the meta.yaml file for the metapackage indicates that the package's content is BSD licensed, so a license file should be present for that reason.

**Comment by jakirkham** [comment]
So I agree @pelson that this does feel a tad extreme. Though I'm not sure what the maintenance burden is after the initial change.

Then again I agree with @tylere that we did put it under the BSD 3-Clause license. In the end, there still will be a package directory after the user installs it with the recipe (even if there is no real library or anything that this pulls in). 

It is also worth noting this will require a total rebuild of the BLAS using stack to ensure it includes the new package with the license because of [version pinning]( https://github.com/conda-forge/numpy-feedstock/blob/4a7436d363562e8b9c9afa786f4456b0af39f060/recipe/meta.yaml#L30 ), which is a bit painful. That being said, many of the packages that need to rebuilt also need to include the license. So this could be a good opportunity to fix all of them as well. It might also prove as a nice test run of how BLAS works in our stack.

**Comment by pelson** [comment]
> Though I'm not sure what the maintenance burden is after the initial change.

That is how all maintenance burden conversations start 😄 

> In the end, there still will be a package directory after the user installs it with the recipe

I'm not sure I follow. In the prefix, or in the package cache?

> It is also worth noting this will require a total rebuild of the BLAS using stack

Not a great place to be, but I believe you are correct.

> That being said, many of the packages that need to rebuilt also need to include the license. So this could be a good opportunity to fix all of them as well.

I'm all for fixing. We don't need to force the matter with adding a License to this package IMO though. 


> meta.yaml file for the metapackage indicates that the package's content is BSD licensed, so a license file should be present for that reason.

In many ways, the reason we did this was to satisfy our headstrong linter (bot) that demands a license to be defined. We don't need to license an empty directory, so I'm hoping we can find the necessary metadata for you to be able to identify this kind of package as an empty metapackage (much like nomkl I believe).

**Comment by jakirkham** [comment]
Let me preface this with I think we have more pressing issues on our plate and am quite happy to table this one. Especially when looking at the scope.

> > Though I'm not sure what the maintenance burden is after the initial change.

> That is how all maintenance burden conversations start 😄 

Guess I'm not planning on changing the license or how it is added. So figured this was pretty much a one time issue.

> > In the end, there still will be a package directory after the user installs it with the recipe

> I'm not sure I follow. In the prefix, or in the package cache?

In the package cache.

> > That being said, many of the packages that need to rebuilt also need to include the license. So this could be a good opportunity to fix all of them as well.

> I'm all for fixing. We don't need to force the matter with adding a License to this package IMO though.

Ah, maybe there was some confusion. Not trying to force anything. Just stating that the burden of the rebuild might not be so bad as we need to do it anyways. So we can just sync these two efforts up.

> > meta.yaml file for the metapackage indicates that the package's content is BSD licensed, so a license file should be present for that reason.

> In many ways, the reason we did this was to satisfy our headstrong linter (bot) that demands a license to be defined. We don't need to license an empty directory, so I'm hoping we can find the necessary metadata for you to be able to identify this kind of package as an empty metapackage (much like nomkl I believe).

If that is the only concern, we could put NA, Public Domain, or similar. Can't remember if that had come up already when adding these.

**Comment by isuruf** [comment]
Fixed
