### ISSUE TITLE
Use libopenblas instead of openblas

### ISSUE THREAD

**Issue by isuruf** [conda-forge/blas-feedstock#31]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jakirkham** [comment]
Is there a way to make a migrator that changes the package used?

cc @CJ-Wright

**Comment by isuruf** [comment]
@jakirkham, downstream packages don't need to change `openblas` to `libopenblas`. Only this package.

**Comment by jakirkham** [comment]
Ah right, that does make things much easier. 😄

**Comment by CJ-Wright** [comment]
@jakirkham Yes I think it is possible to do that (even if it isn't needed in this case, see the [JS](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L396) migrator where we rewrote the build instructions.

**Comment by jakirkham** [comment]
Thanks for the pointer. Good to know that is an option! 👍

**Comment by isuruf** [comment]
Done in #32
