### ISSUE TITLE
No issue really. Just a question about Blas build versions (14_openblas to 15_openblas)

### ISSUE THREAD

**Issue by milljm** [conda-forge/blas-feedstock#42]
Issue: How to depend on a certain build of Blas

With the recent bump in blas build version (14_openblas to 15_openblas but retaining Blas version), something I am maintaining a separate channel for internal individuals broke (a special build of PETSc).

I am curious, if I wanted to tag this latest version/build moving forward, is there a way to do so? I understand the conda_build_config.yaml allows for version control. But does it also allow for build version control?

Thanks in advance for any response you provide!

**Comment by milljm** [comment]
My recipes (if it helps):

  https://github.com/idaholab/conda-moose

**Comment by jakirkham** [comment]
I'm guessing you already read [this doc]( https://conda-forge.org/docs/maintainer/knowledge_base.html#blas ) 🙂

**Comment by isuruf** [comment]
`libblas=3.8.0=15_openblas` if you are using conda cli or in `conda_build_config.yaml`
```
libblas:
  - 3.8.0 15_openblas
```
I'm curious. What broke between the two build numbers?

**Comment by milljm** [comment]
Thank you! This is exactly what I _thought_ I wasn't allowed to do... I will cherish that document link...

The error? Oh nothing you did wrong... Just the normal error when a library goes missing during runtime:

```bash
dyld: Library not loaded: @rpath/libopenblasp-r0.3.8.dylib
  Referenced from: /Users/me/projects/testing/./a.out
  Reason: image not found
zsh: abort      ./a.out
```

**Comment by isuruf** [comment]
Ah, you are directly linking against openblas. The doc linked above gives a good explanation of why we don't directly link against openblas.

**Comment by milljm** [comment]
Not going to pretend to say I know exactly what I am doing... but I am trying to duplicate pets-feedstock, but add things we need to that (mpi support, superlu, parmetis, metis, or some other crontib I don't know off the top of my head at the moment). I'll certainly take another look PETSc's feedstock recipe. I thank you again for your responses! I have a lot learn.
