### ISSUE TITLE
Providing lapack.pc

### ISSUE THREAD

**Issue by moorepants** [conda-forge/blas-feedstock#58]
Issue:

In https://github.com/conda-forge/openblas-feedstock/pull/22 it seems blas.pc, cblas.pc, and lapack.pc were provided with this feedstock. At some point this changed (I haven't found that commit yet) and these are no longer provided. Shouldn't this package provide lapack.pc, for example? This was helpful to downstream packages that rely on pkg-config.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by moorepants** [comment]
Ok, so, they are missing?

**Comment by isuruf** [comment]
yes, they are missing

**Comment by moorepants** [comment]
Thanks @isuruf.
