### ISSUE TITLE
Relax exact pins on windows

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/blas-feedstock#73]
Not sure why this is necessary, e.g. in https://github.com/conda-forge/blas-feedstock/blob/master/recipe/meta.yaml#L66-L69

Do we really need the `exact=win` in the following:
```
      run:
        - {{ pin_compatible("libopenblas", max_pin="x.x.x", exact=win) }}  # [blas_impl == 'openblas']
        - {{ pin_compatible("mkl", max_pin="x", exact=win) }}              # [blas_impl == 'mkl']
        - {{ pin_compatible("blis", max_pin="x.x.x", exact=win) }}         # [blas_impl == 'blis']
```

cf. also this [comment](https://github.com/conda-forge/blis-feedstock/pull/23#issuecomment-872886936)

**Comment by isuruf** [comment]
Because the DLLs are copied instead of symlinked.
