### ISSUE TITLE
blas.pc/lapack.pc not available for all variants

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/blas-feedstock#84]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

This issue mainly manifests when using `libblas` and `liblapack` with projects that generate their pkg-config files via `meson` (only recent versions). In case `meson` detects the presence of a pkg-config file matching a library name or in case the library was found as pkg-config dependency, it will use those in `Require:` rather than add `-lblas`/`-llapack` to the `libs:` section. This breaks the generated pkg-config files when the project is installed with OpenBLAS or MKL variants of `libblas`/`liblapack`, because the `blas.pc` and `lapack.pc` files are only available with the netlib variant.

I'm currently working around this issue by mangling the `blas.pc` and `lapack.pc` files in the `$PREFIX` when building with meson and restoring them after my build script succeeds, which is kind of hacky. It would be nice to have the pkg-config files available with all variants of `libblas`/`liblapack` since relying on them is easier than avoiding them.

Sorry for this very convoluted issue, took me quite some time to figure this out.

**Comment by isuruf** [comment]
You need `blas-devel` which has the pkg-config files for openblas.

**Comment by awvwgk** [comment]
`blas-devel` would go into host, right?

**Comment by isuruf** [comment]
Yes. Btw, if it's a conda-forge recipe, you should build with netlib variant.

**Comment by awvwgk** [comment]
This issue shows up at runtime if a user tries to build against the conda environment which uses MKL or OpenBLAS.

**Comment by isuruf** [comment]
In that case, the user should install `blas-devel`

**Comment by awvwgk** [comment]
Sounds good to me.

Is it worth to mention `blas-devel` and pc files in the docs? Didn't find anything on this except in the recipe here (https://conda-forge.org/docs/search.html?q=blas-devel).

**Comment by isuruf** [comment]
Yes, a PR to docs would be great to have.

**Comment by rgommers** [comment]
This doesn't sound correct or complete to me. I can build SciPy just fine with Meson 0.61.1 (latest) against `openblas` without have `blas-devel` installed.
```
$ conda list blas
# packages in environment at /home/rgommers/anaconda3/envs/scipy-dev:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
openblas                  0.3.17          pthreads_h4748800_1    conda-forge

$ pkg-config --libs openblas
-L/home/rgommers/anaconda3/envs/scipy-dev/lib -lopenblas
(scipy-dev) rgommers@machine:~/code/scipy (meson_option1)$ pkg-config --cflags openblas
-I/home/rgommers/anaconda3/envs/scipy-dev/include

$ locate openblas.pc
/home/rgommers/anaconda3/envs/scipy-dev/lib/pkgconfig/openblas.pc
```

I think `blas-devel` may be needed to build against the Netlib flavors, but not against OpenBLAS?
