### ISSUE TITLE
AMD BLAS

### ISSUE THREAD

**Issue by ngam** [conda-forge/blas-feedstock#88]
### Comment:

I am not really sure looking at this feedstock (and others) if we package the AMD BLAS libraries. Is this so or not? Are they way too specific for us to package them?

https://developer.amd.com/amd-aocl/blas-library/

**Comment by isuruf** [comment]
We already do have `blis` and AMD BLAS is a fork of that. Not sure if it's worth having the two. If so, we can have it.

**Comment by ngam** [comment]
> We already do have `blis` and AMD BLAS is a fork of that. Not sure if it's worth having the two. If so, we can have it.

Ah, good to know! Thanks. I will play around to see if it makes any difference. I will test locally first. Closing here :)
