### ISSUE TITLE
Support mkl 2023.0.0

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/blas-feedstock#94]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

mkl 2023.0.0 is available, but no version of libblas currently supports it

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/blas-feedstock/pull/102
